name: Mapper_2
version: 1.0.0
main: com.github.tckz916.mapper.Mapper

commands:
    mapper:
        description: Mapper Command
        aliases: m
    putchest:
        description: Putchest Command
        aliases: pc
    clearchest:
        description: Clearchest Command
        aliases: cc
    playerhead:
        description: Playerhead Command
        aliases: ph
    getmaterial:
        description: Material Command
        aliases: gm
    enchantment:
        description: Enchantment Command
        aliases: e
    getenchantment:
        description: Getenchantment Command
        aliases: ge
    setname:
        description: Setname Command
        aliases: sn
    setlore:
        description: Setlore Command
        aliases: sl
